apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-1-ingress
  # labels:
  #   app: app-1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  # ingressClassName: app-1
  rules:
  - http:
      paths:
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: app-1
            port: 
              number: 8080

