apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2-dep
  labels:
    app: nginx-canary
spec:
  selector:
    matchLabels:
      app: nginx-canary
  template:
    metadata:
      labels:
        app: nginx-canary
    spec:
      containers:
      - name: nginx-canary
        image: ghcr.io/denoslab/ensf400-sample-app:v2
        ports:
        - containerPort: 8888