apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.cfg: |
    upstream backend {
      server app-1:8888;
      server app-2:8888;
    }

    server {
      location / {
        proxy_pass http://backend;
      }
    }